### ISSUE TITLE
mSerial.begin(FTDriver.BAUD9600) crashes app if no device present

### ISSUE THREAD

**Issue by sequoia-hope** [ksksue/FTDriver#1]
I'm working with a copy of FTSampleTerminal that I have modified a bit. I haven't tried it on the unmodified version but I noticed on my version that the app would crash if there was no FTDI device plugged into the tablet.

I found that the FTDriver.begin method will crash at:

setFTDIEndpoints(mInterface)

if mInterface is null.

adding:

if(mInterface==null)
             return false;

above:

if(!setFTDIEndpoints(mInterface)){
            return false;
        }

seems to fix the issue. Not sure if thats the correct way to do it though as I'm not the best coder!

**Comment by ksksue** [comment]
thank you.
I fixed it.

**Comment by sequoia-hope** [comment]
Great! Glad to help.
