### ISSUE TITLE
import code into eclipse issue

### ISSUE THREAD

**Issue by nova1529** [ksksue/FTDriver#10]
I download the FTDriver-master.zip for test my device is work with the simple code.
But when I import the code into eclipse where comes a few problem. The problem is that the tutorial project can't import jp.ksksue.driver.serial.FTDriver

So how can I import FTDriver into tutorial?

Sorry about asking this but if there is an answer for me that will be thankful.

**Comment by ksksue** [comment]
See tutorial project's property -> Android -> Library
http://ksksue.com/wiki/lib/exe/detail.php?id=wiki%3Aandroid%3Ahardware%3Ausb%3Aftdriver&media=wiki:ftdriver:reference.png
