### ISSUE TITLE
I have Problem in send data...

### ISSUE THREAD

**Issue by javadghane** [ksksue/FTDriver#13]
HI , when i am send a buffer with this code :

``` java
  String wbuf = etw.getText().toString();
        // etw is edittextbox
        mSerial.write(wbuf.getBytes());
```

and in system i open terminal usb ; and connect. when i send in terminal i receive different data. 
 1 - e.g when i send "a" i receive "O" and  sending is continue and not stooped.(after send data receive"0" Tandem. )  
2 - and when i send "a@#$%&*-+()" revive "Oå·µ³«¥…¯­" and not resuming sending "0" such as Previous example. 
- how i can send string or one character that i receive same char or string and sending "0" is stop like as 2 e.g. 

in System i use terminal v1.9b . and use wintouch q74 tablet + xperia pro (android 4.0.4).

感謝

**Comment by ksksue** [comment]
Please check
1. a baud-rate
2. connection GND each other
Did you try a FTDriverTutorial1 project?

**Comment by javadghane** [comment]
baud rate is set on 9600 bps 
i am use "FTDriverTutorial1" but this app also send one data and System revive different data.
Are there Char that can stop the sending "0" after sending is finished?
i test on "Slick USB 2 Serial Term Pro " when send "0" after a string , such as  "a0" or "b0" in System revive different data but sending "0" is not resuming . 
感謝

**Comment by ksksue** [comment]
USB Serial Monitor Lite works good? or not good?
https://play.google.com/store/apps/details?id=jp.ksksue.app.terminal

What chip do you use? model number? FTDI?

**Comment by javadghane** [comment]
i am living in iran and not access to google play . 
i am using a comport to usb cable (FT232R USB UART) . 
usb is connect in android and comport is connect to system .

**Comment by ksksue** [comment]
Download form here
https://github.com/ksksue/Android-USB-Serial-Monitor-Lite/blob/master/AndroidUSBSerialMonitorLite/bin/Android%20USB%20Serial%20Monitor%20Lite.apk

FT232R is supported. It's OK.

**Comment by javadghane** [comment]
i am using app and receive this result: 
![usb1](https://f.cloud.github.com/assets/2885866/870357/6e3e8d28-f82a-11e2-9232-9adc969942a2.jpg)
![usb2](https://f.cloud.github.com/assets/2885866/870358/75015c1c-f82a-11e2-9c21-61e70d21cdd8.png)

in coding how to stooped sending "0" ? (like picture 1)
and Not possible when send "a0" or "a" revive "a" or "a0" in System ?

**Comment by ksksue** [comment]
I think it's hardware problem because USB Serial Monitor Lite is used by a lot of people and works good.

I see
Android -> PC : OK
PC -> Android : NG

PC -> Android's voltage level is ok?

Did you try loop back test?
Android -> FT232R(TX) -> FT232R(RX) -> Android (use one FT232R, one Android)
or PC -> TX -> RX -> PC

Or can you see me hardware picture?

**Comment by javadghane** [comment]
yes i see the hardware pic. 

i  forced to use send a char and put "0" after there .and that is Useful . 
and is Sufficient for my work.

problem is side of my work . if i solved the problem  Notice to you. 

thnks a lot. for supporting.
