### ISSUE TITLE
Unable to read a single byte properly

### ISSUE THREAD

**Issue by honeyws** [ksksue/FTDriver#6]
When I use the FTDriver and read 100 bytes at a time the data comes back properly but I need to read the responses a single byte at a time and this does not function properly for me. How can I read only a single byte at a time?

**Comment by ksksue** [comment]
``` java
byte[] rbuf = new byte[1];
mSerial.read(rbuf);
```

**Comment by honeyws** [comment]
I have tried that. It does not read it properly.

```
            while (!done)
            {
                w.Start(); // while data is coming in, do not time out
                byte[] rBuf = new byte[1];
                SerialPort.read(rBuf);
                //Log.Debug("bytes Read = ", bytesRead.ToString());
                byte b = rBuf[0];
                Log.Debug("b=",ToHex(b));
                if (receive_index == 0)
                {
                    if (b == "somebyte")
                    {
                        seen = true;
                    }

                }
```

But if I simply do a read into a 100 byte array it gets everything properly.

```
          while (!done)
            {
                w.Start(); // while data is coming in, do not time out
                byte[] rBuf = new byte[100];
                SerialPort.read(rBuf);
            }
```

Any thoughts? Have you successfully read one byte at a time? Do I need
to clear the some sort of receive buffer in between each read?

Thanks,

Wesley

**Comment by ksksue** [comment]
Thank you for reports. I just fixed the bug that is caused by a miscalculation of an inner buffer offset on FTDriver class. Please clone and try it.

**Comment by johanlasses** [comment]
Great job ksksue! Your driver works really well for me (except some issues, not clear if it is the driver). 

We use it a little bit different than your examples, we collect messages from the serial port and consumes them within the application. We dont just write them out to a textview. Do you have any recommendations how to send a complete message to the application when "CR" is detected in the buffer. I used a Stringbuilder (mText) to build up the message until CR arrives. Here is some code..

``` java
void readSerialData(byte[] rbuf, int len) {
        for (int i = 0; i < len; ++i) {
            // Look for end char CR.
            if ((rbuf[i] == 0x0D)) {
                //Message complete, send message out of this loop.
                String sentCommand = mText.toString();
                mText.setLength(0);
                if(sentCommand.startsWith("T")){
                    Log.i(TAG, "New message from CAN bus! '" + sentCommand + "'");
                    CanMessage message = new CanMessage(sentCommand);
                    Log.i(TAG, "Can Message Description: " + message.describe());
                    // Fire event! Should be catched in Service
                    eventManager.fire(new CanEvent(message));
                }else{
                    Log.i(TAG, "Standard Serial Message: " + sentCommand);
                }

            } else {
                //Append char to our message
                mText.append((char) rbuf[i]);
            }
        }
    }
```

**Comment by honeyws** [comment]
I have tried it with the new code and it is working. Thank you for the quick response!!

**Comment by ksksue** [comment]
->johanlasses
It looks like there are no problems.
Doesn't this code work?

**Comment by johanlasses** [comment]
I think the problem is somewhere else in my code.

Will try some more.

Thanks.

24 maj 2013 kl. 23:19 skrev Keisuke SUZUKI notifications@github.com:

**Comment by johanlasses** [comment]
I found my problem. I was receiving the wrong length from the serial read. To fix it I just break the for loop when I reach my Linebreak (CR). I have not debugged into the driver to locate the length error.

**Comment by ksksue** [comment]
Do you mean that there is an issue that FTDriver's read() function returns wrong length? Or is it just your code's problem?

**Comment by johanlasses** [comment]
This was my code doing the wrong stuff. Thanks.

2013/5/29 Keisuke SUZUKI notifications@github.com

**Comment by ksksue** [comment]
OK I see. Good luck.

**Comment by honeyws** [comment]
Hi,

The FTDriver is working great, but I am running into issues getting
responses from a particular piece of hardware I am using. Is there a way to
clear the read buffer or is that handled automatically?

Thank you,
Wesley
